# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0003_bancoinformacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bancoinformacion',
            options={'verbose_name_plural': 'Banco de informaci\xf3n'},
        ),
        migrations.AlterField(
            model_name='sexo',
            name='nombre',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50),
        ),
    ]
