# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0005_auto_20181004_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
