# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0006_voluntario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
