# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0008_auditoria_contactanos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BancoInformacion',
            new_name='Banco_Informacion',
        ),
        migrations.RenameModel(
            old_name='EstructuraOrganizativa',
            new_name='Estructura_Organizativa',
        ),
        migrations.RenameModel(
            old_name='PreguntasFrecuentes',
            new_name='Preguntas_Frecuentes',
        ),
        migrations.RenameModel(
            old_name='TipoVoluntario',
            new_name='Tipo_Voluntario',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='fechaHora',
            new_name='fecha_Hora',
        ),
    ]
