# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-03 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0009_auto_20181030_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
