# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-03 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0010_auto_20181102_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='foto',
            field=models.ImageField(upload_to='fotos_voluntarios'),
        ),
    ]
