# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0012_auto_20181120_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_voluntario',
            name='tipo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
