# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0014_auto_20181120_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_voluntario',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
