# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0015_auto_20181121_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco_informacion',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
