# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0016_banco_informacion_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='voluntario',
            new_name='voluntarios',
        ),
    ]
