# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0019_auto_20181122_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
