# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0020_evento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
