# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0021_auto_20181129_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
