# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0022_auto_20181129_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
    ]
